#!/usr/bin/env bash
#~internal: commit any changes to the given command since last invocation

set -euo pipefail

# might be first run...
mkdir -p "$YNOT_CUSTOM"
cd "$YNOT_CUSTOM"
# this will reinitialize git templates but otherwise idempotent;
# if a custom template causes an issue, it could just as easily do that the first time
# also, --quiet is not very quiet for some reason...
git init --initial-branch=ynot-custom --quiet 1>/dev/null 2>/dev/null
