#!/usr/bin/env bash
#~ynot one-time installation script

set -euo pipefail

echo
echo Checking for dependencies...

if [ -z "${HOME:-}" ]; then
    echo
    echo "Error: environment variable "HOME" not set" >&2
    exit 1
fi

MISSING_DEPS="false"
for REQD_CMD in basename chmod column cp echo env find flock git ln mv paste realpath rm xargs; do
    CMD_PATH="$(which "$REQD_CMD" || true)"
    if [ -z "$CMD_PATH" ]; then
        # you're probably on macOS IDK
        echo "missing: '$REQD_CMD'"
        MISSING_DEPS="true"
    fi
done
if [ "$MISSING_DEPS" == "true" ]; then
    echo
    echo "Error: one or more required dependencies are missing;" >&2
    echo "make sure they're installed and try installing ynot again." >&2
    exit 1
else
    echo "All dependencies found!"
fi

# YAGNI: separate behavior for macOS?
DEFAULT_YNOT_DIR="$HOME/.local/share"     # directory where ynot will be located
DEFAULT_SYMLINK_DIR="$HOME/.local/bin"    # directory where the symlink will be located; must be on the path
WHICH_YNOT_BEFORE="$(which ynot || true)" # test for command conflict - don't care if this fails
if [ ! -z "$WHICH_YNOT_BEFORE" ]; then
    echo "Error: a 'ynot' command already exists at '$WHICH_YNOT_BEFORE'" >&2
    exit 1
fi

echo
echo Choose where you want ynot installed, or press enter to acccept the defaults.
echo
read -rp "Directory that will contain ynot; can go anywhere ($DEFAULT_YNOT_DIR): " YNOT_DIR
read -rp "Directory that will hold the symlink; must be on your path ($DEFAULT_SYMLINK_DIR): " SYMLINK_DIR

YNOT_DIR="${YNOT_DIR:-$DEFAULT_YNOT_DIR}"
YNOT_ROOT="$YNOT_DIR/ynot" # the directory that will contain the ynot checkout
YNOT_PATH="$YNOT_ROOT/ynot" # the ynot executable itself
YNOT_PREPARE_SESSION_SCRIPT="$YNOT_ROOT/runtime/prepare-bash-session" # script to set completions etc.

SYMLINK_DIR="${SYMLINK_DIR:-$DEFAULT_SYMLINK_DIR}"
YNOT_SYMLINK="$SYMLINK_DIR/ynot"  # symlink name matches executable

# check prerequisite environment
if [ ! -d "$YNOT_DIR" ]; then
    echo
    echo "Error: '$YNOT_DIR' is not a directory" >&2
    exit 1
fi
if [ ! -d "$SYMLINK_DIR" ]; then
    echo
    echo "Error: '$SYMLINK_DIR' is not a directory" >&2
    exit 1
fi
if [ -e "$YNOT_ROOT" ]; then
    echo
    echo "Error: '$YNOT_ROOT' already exists" >&2
    exit 1
fi
if [ -e "$YNOT_SYMLINK" ]; then
    echo
    echo "Error: '$YNOT_SYMLINK' already exists" >&2
    exit 1
fi
if [ "$YNOT_SYMLINK" == "$YNOT_ROOT" ]; then
    echo
    echo "Error: symlink and ynot directory cannot be in the same place" >&2
    exit 1
fi
if [[ ! ":$PATH:" == *":$SYMLINK_DIR:"* ]]; then
    echo
    echo "Error: the directory ('$SYMLINK_DIR') that would contain the symlink is not on your path;" >&2
    echo "       please add it to your path or choose somewhere else to place the symlink" >&2
    exit 1
fi

echo
echo "ynot will be installed to: '$YNOT_ROOT'"
echo "ynot will be symlinked from: '$YNOT_SYMLINK'"

# prompt to set up editor if not set up
if [ -z "${EDITOR:-}" ] && [ -z "${VISUAL:-}" ] && [ -z "${YNOT_EDITOR:-}" ]; then
    echo
    echo "Warning: none of the expected environment variables are set to indicate your preferred text editor."
    echo "Provide settings for the following to add them to your ~/.bashrc, or leave blank to configure them manually later:"
    echo
    read -rp "Setting for EDITOR, e.g. nano, vi, joe, vim, emacs, nvim (): " NEW_EDITOR
    read -rp "Setting for VISUAL, e.g. kwrite, kate, gedit, codium/code/cursor/agy (): " NEW_VISUAL
    read -rp "Setting for YNOT_EDITOR, if you want ynot to use something other than EDITOR or VISUAL (): " NEW_YNOT_EDITOR
fi

echo
echo Install ynot?
echo
read -rp "Press enter to perform the installation, or Ctrl-C to exit..." WHATEVER

# perform the installation
echo
if [ ! -z "${NEW_EDITOR+x}" ] || [ ! -z "${NEW_VISUAL+x}" ] || [ ! -z "${NEW_YNOT_EDITOR+x}" ]; then
    echo                                               >> "$HOME/.bashrc"
    echo "# default text editors"                      >> "$HOME/.bashrc"
    if [ ! -z "${NEW_EDITOR+x}" ]; then
        echo "export EDITOR=\"$NEW_EDITOR\""           >> "$HOME/.bashrc"
    fi
    if [ ! -z "${NEW_VISUAL+x}" ]; then
        echo "export VISUAL=\"$NEW_VISUAL\""           >> "$HOME/.bashrc"
    fi
    if [ ! -z "${NEW_YNOT_EDITOR+x}" ]; then
        echo "export YNOT_EDITOR=\"$NEW_YNOT_EDITOR\"" >> "$HOME/.bashrc"
    fi
    echo "Text editor configurations written to $HOME/.bashrc;"
    echo "You'll probably need to 'source $HOME/.bashrc' for them to take effect."
else
    echo "No text editors were configured."
fi

echo
git clone https://github.com/phoneticsushi/ynot.git "$YNOT_ROOT"
cd "$YNOT_ROOT"

echo
echo "Symlinking '$YNOT_SYMLINK' -> '$YNOT_PATH'..."
ln -s "$YNOT_PATH" "$YNOT_SYMLINK"

echo
echo "Loading ynot session state... (bash completions etc.)"
. "$YNOT_PREPARE_SESSION_SCRIPT"  # FIXME: does this break if the user isn't running bash?
echo "Adding session state load to ~/.bashrc..."
echo                                      >> "$HOME/.bashrc"
echo "# ynot bash completion, etc..."     >> "$HOME/.bashrc"
echo ". \"$YNOT_PREPARE_SESSION_SCRIPT\"" >> "$HOME/.bashrc"

# check the installation
echo
echo "Testing that ynot is installed in the path..."
WHICH_YNOT_AFTER="$(which ynot || true)"

if [ -z "$WHICH_YNOT_AFTER" ]; then
    echo "Warning: ynot symlinked from '$YNOT_SYMLINK' but not found in path;" >&2
    echo "Verify the symlink is accessible from your path, then try running 'ynot list'" >&2
    exit 2
fi

REAL_WHICH_YNOT_AFTER="$(realpath "$WHICH_YNOT_AFTER")"
if [ "$REAL_WHICH_YNOT_AFTER" != "$YNOT_PATH" ]; then
    echo "Warning: ynot expected at '$YNOT_PATH' but found at "$REAL_WHICH_YNOT_AFTER";" >&2
    echo "Verify your path and symlink are invoking the correct ynot, then try running 'ynot list'"
    exit 2
fi

# flex on 'em
echo
echo "Finished installing ynot!  Running 'ynot list':"
echo
ynot list
