#!/usr/bin/env bash
#~interactive command selector

set -euo pipefail

# YAGNI: in the future, this could display descriptions, offer an interactive selection, allow search, etc.
# for now, just list:
echo "NYI: in the future, this will be an interactive list;"
echo "delegatng to 'ynot list' for now..."
echo
ynot list
