#!/usr/bin/env bash

set -euo pipefail

# YAGNI: in the future, this could display descriptions, offer an interactive selection, allow search, etc.
# for now, just list:
echo Custom Commands:
ls -1 $YNOT_CUSTOM
echo
echo Provided Commands:
ls -1 $YNOT_PROVIDED
