#!/usr/bin/env bash
#~remove a previously registered custom command

set -euo pipefail

DROP_CMD_NAME="${1:?Usage: $(basename "$0") <command-to-drop>}"

DROP_CMD_PATH="$YNOT_CUSTOM/$DROP_CMD_NAME"

"$YNOT_HELPERS"/check-command-name-valid "$DROP_CMD_NAME"

if [ ! -f "$DROP_CMD_PATH" ]; then
    # more specific error for edge case where command name matches a provided command.
    if [ -f "$YNOT_PROVIDED/$DROP_CMD_NAME" ]; then
        echo "Error: '$DROP_CMD_NAME' is the name of a provided command and provided commands may not be dropped"
        exit 12
    else
        echo "Error: '$DROP_CMD_NAME' is not registered as a custom command"
        exit 1
    fi
fi

# if the custom command being dropped shadows a provided command,
# don't error, just drop it anyway.

# YAGNI: solve for edge cases like "is a directory etc."
# if using ynot to manage state, it should be impossible to get into that situation

"$YNOT_HELPERS/ask-for-confirmation" "Confirm drop for '$DROP_CMD_NAME'"

rm "$DROP_CMD_PATH"
echo "'ynot $DROP_CMD_NAME' -> (deleted)"

# because we're performing a deletion,
# we want to track that immediately in history.
# if the command had never been run, this will fizzle and do nothing.
env YNOT_CUSTOM="$YNOT_CUSTOM" \
    flock "$YNOT_CUSTOM" "$YNOT_HELPERS/commit-custom-command-changes" "$(basename "$0")" "$DROP_CMD_NAME"
