#!/usr/bin/env bash
#~provided: update ynot and provided commands with the latest changes

set -euo pipefail

cd "$YNOT_ROOT"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# default checkout?
if [ "$CURRENT_BRANCH" != "main" ]; then
    echo "Warning: your ynot repo is currently checked out to '$CURRENT_BRANCH', not 'main'."
    "$YNOT_HELPERS/ask-for-confirmation" "Continue anyway?"
fi

# user hasn't changed anything?
if ! git diff --quiet; then
    echo "Warning: the working tree of your ynot repo is dirty; update may fail."
    "$YNOT_HELPERS/ask-for-confirmation" "Continue anyway?"
fi

# leverage linus' latest laboriously liasoned lemonade launcher;
# let this print since it's good info
git pull
