#!/usr/bin/env bash
#~provided: update ynot and provided commands with the latest changes

set -euo pipefail

cd "$YNOT_ROOT"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# default checkout?
if [ "$CURRENT_BRANCH" != "main" ]; then
    echo "Warning: your ynot repo is currently checked out to '$CURRENT_BRANCH', not 'main'."
    "$YNOT_HELPERS/ask-for-confirmation" "Continue anyway?"
fi

# user hasn't changed anything?
if ! git diff --quiet; then
    echo "Warning: the working tree of your ynot repo is dirty; update may fail."
    "$YNOT_HELPERS/ask-for-confirmation" "Continue anyway?"
fi

PROVIDED_BEFORE=$(ls -1 "$YNOT_PROVIDED" | sort)

# leverage linus' latest laboriously liasoned lemonade launcher;
# let this print since it's good info
git pull

PROVIDED_AFTER=$(ls -1 "$YNOT_PROVIDED" | sort)

ONLY_PROVIDED_BEFORE=$(comm -23 <(echo "$PROVIDED_BEFORE") <(echo "$PROVIDED_AFTER"))
ONLY_PROVIDED_AFTER=$(comm -13 <(echo "$PROVIDED_BEFORE") <(echo "$PROVIDED_AFTER"))

# inform user of any provided commands added/removed
if [ ! -z "$ONLY_PROVIDED_BEFORE" ]; then
    echo
    echo Provided commands removed in latest update:
    for CMD in ${ONLY_PROVIDED_BEFORE}
    do
        echo "$CMD"
    done
fi
if [ ! -z "$ONLY_PROVIDED_AFTER" ]; then
    echo
    echo Provided commands added in latest update:
    for CMD in ${ONLY_PROVIDED_AFTER}
    do
        echo "$CMD"
    done
fi

# warn on conflict, but only after all printouts, so loop again:
if [ ! -z "$ONLY_PROVIDED_AFTER" ]; then
    for CMD in ${ONLY_PROVIDED_AFTER}
    do
        env YNOT_PROVIDED="$YNOT_PROVIDED" \
            YNOT_CUSTOM="$YNOT_CUSTOM" \
                "$YNOT_HELPERS/inform-on-conflict" "$CMD"
    done
fi
